### ISSUE TITLE
Custom analytics JS

### ISSUE THREAD

**Issue by XakepSDK** [FriendsOfFlarum/analytics#14]
Please, add ability to put custom analytics JS

**Comment by clarkwinkelmann** [comment]
What would be the difference from using custom HTML ?

**Comment by XakepSDK** [comment]
Custom HTML puts code in top of body. this ext. puts code in bottom of header

**Comment by clarkwinkelmann** [comment]
I don't think it's a use case we want to solve with this extension. A "custom HEAD content" extension would be more logical I think. And it shouldn't be complicated to make.

You can even inject content in HEAD without an extension by using `extend.php`. I can't think of the code you need right now but it's a single call to an existing extender.
