### ISSUE TITLE
Analytics code shows 2 times in page source

### ISSUE THREAD

**Issue by XakepSDK** [FriendsOfFlarum/analytics#15]
I'm seeing script output 2 times
[https://puu.sh/CIvoC/8a7b600531.png](https://puu.sh/CIvoC/8a7b600531.png)

**Comment by clarkwinkelmann** [comment]
That's a strange one... Notice the icon is also there two times.

What happens if you disable the analytics extension ? Is the icon still there two times ?

**Comment by XakepSDK** [comment]
Yep, it works! Thank you. Close if you wish.

**Comment by XakepSDK** [comment]
Flarum SEO extension issue.

**Comment by clarkwinkelmann** [comment]
Adding the link for future reference https://github.com/v17development/flarum-seo/issues/10
