### ISSUE TITLE
Settings Pop-Out disappears

### ISSUE THREAD

**Issue by tankerkiller125** [FriendsOfFlarum/analytics#19]
Everything was working great in beta 9 of flarum, however as of beta 10 the settings Pop-Out will disappear upon trying to enable or disable an analytics service. This makes it impossible to change settings or enable/disable analytics services.

**Comment by clarkwinkelmann** [comment]
Is this still an issue ?

I've seen the modal issue resurfacing regularly on the forums for various reasons. But it does not happen all the time, and doesn't happen to everybody.

I personnaly never experienced it with the Analytics extension.

Most likely it's a Flarum issue.

**Comment by tankerkiller125** [comment]
It appears to be fine in beta.12 now. I'll close this, this may in fact be related to Flarum.
