### ISSUE TITLE
No Analytical Admin Panel Option

### ISSUE THREAD

**Issue by himanshuahuja96** [FriendsOfFlarum/analytics#4]
I am Not able to See analytical Admin Panel Option in Administration Panel..Please solve this or provide fix for this.

Thanks

**Comment by santiagobiali** [comment]
The Analytical panel is only available if you are using PIWIK. If you are using it, please provide more information.

**Comment by himanshuahuja96** [comment]
I have activated the plugin and there is no option for analytics like you have showed in screenshot. I have also posted at discuss flarum community.

**Comment by himanshuahuja96** [comment]
You have replied same there also

**Comment by santiagobiali** [comment]
3 dots should have appeared when you hover Analytics, try erasing your cache.

**Comment by himanshuahuja96** [comment]
There is no link in Dashboard menu I am saying that but the extension is accessible from extension menu

**Comment by clarkwinkelmann** [comment]
I'm closing this issue because it applied to an older version of the extension and Flarum.

Feel free to open a new issue if you experience new problems with the extension.
