### ISSUE TITLE
Error on Uninstall

### ISSUE THREAD

**Issue by XimmersiveX** [FriendsOfFlarum/analytics#5]
POST https://larpny.com/forum/api/extensions/flagrow-analytics

<br />
<b>Warning</b>:  array_key_exists(): The first argument should be either a string or an integer in <b>/home/public_html/forum/vendor/illuminate/support/Collection.php</b> on line <b>1032</b><br />
<br />
<b>Catchable fatal error</b>:  Argument 1 passed to Flarum\Extension\ExtensionManager::migrateDown() must be an instance of Flarum\Extension\Extension, null given, called in /home/public_html/forum/vendor/flarum/core/src/Extension/ExtensionManager.php on line 164 and defined in <b>/home/public_html/forum/vendor/flarum/core/src/Extension/ExtensionManager.php</b> on line <b>238</b><br />

**Comment by luceos** [comment]
This extension is not compatible with the latest Flarum. Once a stable Flarum is released, all extensions will be updated to work again.

**Comment by clarkwinkelmann** [comment]
Closing this issue because it applied to an older version of the extension and was most likely fixed.
