### ISSUE TITLE
Dark theme compatibility 

### ISSUE THREAD

**Issue by 0E800** [FriendsOfFlarum/analytics#8]
Thank you for the excellent extension. Any chance  you can have it be "Dark Theme" compatile in future builds?

Best regards,

**Comment by clarkwinkelmann** [comment]
I'm digging through the old issues.

Would you say it's still relevant ?

Which parts would need to be made compatible ? The settings modal uses Flarum components that should work with dark mode. The Piwik/Matomo embed is an iframe and we have no control over the Piwik theme.

**Comment by clarkwinkelmann** [comment]
I'm going to close this for inactivity. Feel free to re-open with more details.
