### ISSUE TITLE
Analytics not showing up

### ISSUE THREAD

**Issue by 1337god** [FriendsOfFlarum/analytics#9]
Settings:
![image](https://cloud.githubusercontent.com/assets/18701229/22626548/b71bf548-eba7-11e6-8800-4edd0298c90c.png)
(When I try to disable some settings even when saving they come back)

Admin Panel:
![image](https://cloud.githubusercontent.com/assets/18701229/22626553/c66ef48c-eba7-11e6-8914-71de212d3c65.png)

Frame Link:
![image](https://cloud.githubusercontent.com/assets/18701229/22626554/cf22d800-eba7-11e6-8b97-cf50851d3207.png)

**Comment by luceos** [comment]
What version of piwik are you running?

**Comment by 1337god** [comment]
The last one, 3.0.1 to be exact. @Luceos

**Comment by luceos** [comment]
I think this extension was never meant for version 3. Embedding might have changed with the release of this major version.

**Comment by 1337god** [comment]
Oh ok thank you!

**Comment by clarkwinkelmann** [comment]
Closing this issue because it applied to an older version of the extension and Flarum.

Feel free to open a new issue if you still experience problems.
